---
- name: Practice ansible_facts
  hosts: all
  gather_facts: True
  tasks:
  - name: 練習ansible_facts
    debug:
      msg:
      - "這是第一行"
      - "這是第二行"
      - "這是第三行"

  - name: 顯示主機相關資訊
    debug:
      msg:
      - 主機名稱 = " {{ ansible_hostname }} "
      - 主機作業系統家族 = " {{ ansible_os_family }} "
      - 處理器 = " {{ ansible_processor }} "
      - 主機 硬碟資訊 = " {{ ansible_devices }} "
      - 主機 IPv4 = " {{ ansible_all_ipv4_addresses }} "
      - 主機 SELINUX 狀態 = " {{ ansible_selinux }} "

########################
# groups 與 group_names #
########################
# groups	列出 inventory 中所有的主机和主机组
# group_names	列出托管主机所在的所有组
########################

- name: 顯示 groups
    debug:
      msg: " {{ groups }} "

  - name: 顯示 group_name
    debug:
      msg: " {{ group_names }} "

############
# hostvars #
############

  - name: 顯示 hostvars
    debug:
      msg:
      - 192.168.50.201 的 IP {{ hostvars['192.168.50.201']['ansible_default_ipv4']['address'] }}
      - 192.168.50.202 的 IP {{ hostvars['192.168.50.202']['ansible_default_ipv4']['address'] }}
      - 192.168.50.203 的 IP {{ hostvars['192.168.50.203']['ansible_default_ipv4']['address'] }}
      - 192.168.50.204 的 IP {{ hostvars['192.168.50.204']['ansible_default_ipv4']['address'] }}

#################################
# inventory_dir 與 playbook_dir #
#################################

  - name: 顯示 inventory_dir 與 playbook_dir
    debug:
      msg:
      - " {{ inventory_dir }} "
      - " {{ playbook_dir }} "

