---
- name: practice template
  hosts: all
  become: True
  tasks:
  - name: copy template
    template:
      src: ./iptables.sh
      dest: ~/iptables.sh
      owner: root
      group: root
      mode: 0655
