---
- name: install nginx
  hosts: all
  become: true
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest
  - name: start nginx
    service:
      name: nginx
      state: started
  - name: get 80 ok
    uri:
      url: http://127.0.0.1
      return_content: yes
    register: URI_80
  - name: debug URI_80
    debug:
      var: URI_80
 - name: start nginx
    service:
      name: nginx
      state: removed 
